version: '3.4'

services:

  identitydb:
    container_name: identitydb
    user: root
    environment: 
      - SA_PASSWORD=ID2022Entity
      - ACCEPT_EULA=Y
    restart: always
    ports: 
      - "1433:1433"
    volumes: 
      - identitydb_data:/var/opt/mssql/data

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityConnectionString:Server=identitydb;Database=Identitydb;User Id=sa;Password=ID2022Entity;"
    depends_on:
      - identitydb
    ports:
      - "4000:80"

  shoppingcart.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  wishlist.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

