version: '3.4'

services:

  wishlistdb:
    container_name: wishlistdb
    restart: always
    ports:
      - "6379:6379"

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"


  identitydb:
    container_name: identitydb
    user: root
    environment: 
      - SA_PASSWORD=ID2022Entity
      - ACCEPT_EULA=Y
    restart: always
    ports: 
      - "1433:1433"
    volumes: 
      - identitydb_data:/var/opt/mssql/data

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityConnectionString:Server=identitydb;Database=Identitydb;User Id=sa;Password=ID2022Entity;"
    depends_on:
      - identitydb
    ports:
      - "4000:80"

  catalog.grpc:
    container_name: catalog.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8001:80"
    depends_on:
      - catalogdb

  wishlist.api:
    container_name: wishlist.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=wishlistdb:6379"
      - "GrpcSettings:DiscountUrl=http://catalog.grpc"
    depends_on:
      - wishlistdb
      - catalog.grpc
    ports:
      - "8002:80"
