version: '3.4'

services:
  catalogdb:
    image: mongo

  wishlistdb:
    image: redis:alpine

  shoppingcartdb:
    image: redis:alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

  catalog.grpc:
    image: ${DOCKER_REGISTRY-}cataloggrpc
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Grpc/Dockerfile

  wishlist.api:
    image: ${DOCKER_REGISTRY-}wishlistapi
    build:
      context: .
      dockerfile: Services/WishList/WishList.API/Dockerfile
  
  shoppingcart.api:
     image: ${DOCKER_REGISTRY-}shoppingcartapi
     build:
        context: .
        dockerfile: Services\ShoppingCart\ShoppingCart.API\Dockerfile

  shoppingcart.grpc:
    image: ${DOCKER_REGISTRY-}shoppingcartgrpc
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.Grpc/Dockerfile

  library.api:
     image: ${DOCKER_REGISTRY-}libraryapi
     build:
        context: .
        dockerfile: Services/Library/Library.API/Dockerfile
  
  librarydb:
     image: mongo
     command: mongod --port 27018
  

<<<<<<< Updated upstream
=======
  spagateway:
    image: ${DOCKER_REGISTRY-}spagateway
    build:
      context: .
      dockerfile: ApiGateways/SPAGateway/Dockerfile

  mailservice:
    image: ${DOCKER_REGISTRY-}mailservice
    build:
      context: .
      dockerfile: Services/MailService/Dockerfile

  maildb:
    image: mongo


>>>>>>> Stashed changes
volumes:
  mongo_data: 
  identitydb_data:
  librarydb_data: 
  maildb_data:


