version: '3.4'

services:

  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

  shoppingcart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.API/Dockerfile

  wishlist.api:
    image: ${DOCKER_REGISTRY-}wishlistapi
    build:
      context: .
      dockerfile: Services/WishList/WishList.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  identitydb_data:


